import { PDFDocument, rgb, StandardFonts } from "pdf-lib"

import fs from "fs"

import path from "path"

import { db, initDatabase } from "../server/db/database"

const uploadDir = path.resolve(process.cwd(), "uploads")

if (!fs.existsSync(uploadDir)) {
  fs.mkdirSync(uploadDir, { recursive: true })
}

async function createPDF(
  title: string,

  course: string,

  type: string,

  author: string,

  sections: { heading: string lines: string[] }[],
): Promise<string> {
  const pdfDoc = await PDFDocument.create()

  const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold)

  const fontRegular = await pdfDoc.embedFont(StandardFonts.Helvetica)

  const page = pdfDoc.addPage([595.28, 841.89]) // A4

  const { width, height } = page.getSize()

  // Header Banner (Navy #061B49)

  page.drawRectangle({
    x: 0,

    y: height - 100,

    width: width,

    height: 100,

    color: rgb(6 / 255, 27 / 255, 73 / 255),
  })

  // Header Title

  page.drawText("StudyStack — IIT Roorkee", {
    x: 40,

    y: height - 50,

    size: 22,

    font: fontBold,

    color: rgb(1, 1, 1),
  })

  page.drawText("Your Stack. Your Track. · Academic Resource Portal", {
    x: 40,

    y: height - 75,

    size: 11,

    font: fontRegular,

    color: rgb(85 / 255, 199 / 255, 255 / 255), // Cyan
  })

  // Resource Title Box

  page.drawRectangle({
    x: 40,

    y: height - 170,

    width: width - 80,

    height: 55,

    color: rgb(245 / 255, 248 / 255, 252 / 255),

    borderColor: rgb(20 / 255, 110 / 255, 245 / 255),

    borderWidth: 1.5,
  })

  page.drawText(title, {
    x: 55,

    y: height - 140,

    size: 15,

    font: fontBold,

    color: rgb(15 / 255, 23 / 255, 42 / 255),
  })

  page.drawText(
    `Course: ${course}  |  Category: ${type}  |  Contributed by: ${author}`,

    {
      x: 55,

      y: height - 158,

      size: 10,

      font: fontRegular,

      color: rgb(100 / 255, 116 / 255, 139 / 255),
    },
  )

  // Body content

  let currentY = height - 205

  for (const sec of sections) {
    page.drawText(sec.heading, {
      x: 40,

      y: currentY,

      size: 13,

      font: fontBold,

      color: rgb(20 / 255, 110 / 255, 245 / 255),
    })

    currentY -= 20

    for (const line of sec.lines) {
      page.drawText(line, {
        x: 45,

        y: currentY,

        size: 10,

        font: fontRegular,

        color: rgb(51 / 255, 65 / 255, 85 / 255),
      })

      currentY -= 16
    }

    currentY -= 12
  }

  // Footer

  page.drawText(
    "Verified Academic Document · Generated by StudyStack for IIT Roorkee Students",

    {
      x: 40,

      y: 35,

      size: 9,

      font: fontRegular,

      color: rgb(148 / 255, 163 / 255, 184 / 255),
    },
  )

  const pdfBytes = await pdfDoc.save()

  const filename = `${course.toLowerCase()}_${type.toLowerCase()}_${Date.now()}.pdf`

  const filePath = path.join(uploadDir, filename)

  fs.writeFileSync(filePath, pdfBytes)

  return filename
}

export async function generateAllSamplePDFs() {
  initDatabase()

  const samples = [
    {
      id: 1,

      title: "DSA Mid-Sem Notes 2024",

      course: "CSN-201",

      type: "Notes",

      by: "Arjun Sharma",

      sections: [
        {
          heading: "1. Asymptotic Notations and Complexity",

          lines: [
            "- Big-O (O): Upper bound on the growth rate of runtime.",

            "- Big-Omega (Omega): Lower bound representing best-case scenario.",

            "- Big-Theta (Theta): Tight bound indicating exact asymptotic behavior.",

            "- Master Theorem: T(n) = aT(n/b) + f(n) for divide-and-conquer recurrences.",
          ],
        },

        {
          heading: "2. Linear Data Structures",

          lines: [
            "- Dynamic Arrays: Amortized O(1) append, O(1) random access.",

            "- Linked Lists: Singly, Doubly, and Circular. O(1) insertions at known pointers.",

            "- Stacks: LIFO structure used in call stacks, expression evaluation (Infix to Postfix).",

            "- Queues: FIFO structure, circular queue, double-ended queue (deque).",
          ],
        },

        {
          heading: "3. Trees and Binary Search Trees (BST)",

          lines: [
            "- Binary Tree Traversals: In-order (Left-Root-Right), Pre-order, Post-order, Level-order.",

            "- BST Invariant: Left child < Root < Right child.",

            "- AVL Trees: Self-balancing BST with balance factor in {-1, 0, 1}. Rotations: LL, RR, LR, RL.",
          ],
        },

        {
          heading: "4. Graph Algorithms",

          lines: [
            "- BFS (Breadth-First Search): Queue-based traversal, finds shortest path in unweighted graphs.",

            "- DFS (Depth-First Search): Stack/recursion-based, topological sorting, cycle detection.",

            "- Dijkstra's Algorithm: Shortest path in non-negative weighted graphs using Min-Heap: O((V+E)logV).",
          ],
        },
      ],
    },

    {
      id: 2,

      title: "OS Previous Year Paper 2023",

      course: "CSN-301",

      type: "PYQ",

      by: "Priya Verma",

      sections: [
        {
          heading: "Section A: Process Management and CPU Scheduling",

          lines: [
            "Q1. Differentiate between Shortest Job First (SJF) and Round Robin (RR) scheduling.",

            "    Compute average turnaround time and waiting time for given arrival times.",

            "Q2. Explain the four necessary conditions for Deadlock (Mutual exclusion, Hold and wait,",

            "    No preemption, Circular wait). Show how Banker's Algorithm ensures safety.",
          ],
        },

        {
          heading: "Section B: Memory Management and Paging",

          lines: [
            "Q3. Explain Virtual Memory, Page Faults, and the Inverted Page Table structure.",

            "Q4. Compare Page Replacement Algorithms: FIFO, Optimal (Belady's Anomaly), and LRU.",

            "    Given reference string: 7, 0, 1, 2, 0, 3, 0, 4, 2, 3, 0, 3, 2, 1, 2, 0, 1, 7, 0, 1.",
          ],
        },

        {
          heading: "Section C: File Systems and Synchronization",

          lines: [
            "Q5. Implement the Dining Philosophers Problem solution using Semaphores and Mutex locks.",

            "Q6. Explain inode structure in UNIX and how indirect blocks handle large file sizes.",
          ],
        },
      ],
    },

    {
      id: 3,

      title: "Signals Lab Manual",

      course: "EE-301",

      type: "Labs",

      by: "Rahul Gupta",

      sections: [
        {
          heading: "Lab Experiment 1: Generation of Elementary Signals",

          lines: [
            "- Objective: Plot Unit Step, Unit Impulse, Ramp, and Exponential sequences in Python.",

            "- Key Functions: numpy.heaviside, scipy.signal, matplotlib.pyplot.",

            "- Viva Question: Explain why the continuous Dirac delta function has infinite amplitude at t=0.",
          ],
        },

        {
          heading: "Lab Experiment 2: Linear Convolution and LTI Systems",

          lines: [
            "- Objective: Verify commutative, associative, and distributive properties of convolution sum.",

            "- Formula: y[n] = sum(x[k] * h[n-k]) from k = -infinity to +infinity.",

            "- Analysis: Observe transient response vs steady-state response for FIR filters.",
          ],
        },

        {
          heading: "Lab Experiment 3: Discrete Fourier Transform (DFT)",

          lines: [
            "- Objective: Implement 8-point and 16-point FFT using Cooley-Tukey Radix-2 algorithm.",

            "- Frequency Resolution: Delta_f = Fs / N. Compare zero-padding effect with actual resolution.",
          ],
        },
      ],
    },

    {
      id: 4,

      title: "Maths III Assignment 2",

      course: "MA-201",

      type: "Assignments",

      by: "Neha Singh",

      sections: [
        {
          heading: "Problem Set 1: Fourier Series and Transforms",

          lines: [
            "1. Find the Fourier series expansion of f(x) = x^2 in the interval (-pi, pi).",

            "   Hence deduce that 1/1^2 + 1/2^2 + 1/3^2 + ... = pi^2 / 6.",

            "2. Solve the 1D Heat Conduction Equation du/dt = c^2 (d^2u/dx^2) using separation of variables.",
          ],
        },

        {
          heading: "Problem Set 2: Complex Analysis and Residues",

          lines: [
            "3. Verify Cauchy-Riemann equations in polar coordinates: du/dr = (1/r)dv/dtheta.",

            "4. Evaluate the contour integral of [dz / (z^2 + 1)^2] around |z| = 2 using Residue Theorem.",
          ],
        },
      ],
    },

    {
      id: 5,

      title: "Computer Networks Cheatsheet",

      course: "CSN-401",

      type: "Notes",

      by: "Arjun Sharma",

      sections: [
        {
          heading: "1. OSI Model vs TCP/IP Stack",

          lines: [
            "- Application: HTTP/3 (QUIC), DNS, TLS 1.3, SMTP, SSH.",

            "- Transport: TCP (3-way handshake, sliding window, Congestion Control: Reno/CUBIC), UDP.",

            "- Network: IPv4/IPv6, CIDR Subnetting, ICMP, OSPF (Dijkstra), BGP (Path Vector).",

            "- Data Link: Ethernet framing, CSMA/CD, ARP, MAC addresses, Spanning Tree Protocol (STP).",
          ],
        },

        {
          heading: "2. Essential Network Formulas",

          lines: [
            "- Transmission Delay: T_tx = Packet Size (bits) / Bandwidth (bps).",

            "- Propagation Delay: T_prop = Distance / Speed of light in medium (approx 2 x 10^8 m/s).",

            "- Bandwidth-Delay Product (BDP): BDP = Bandwidth x RTT (Maximum in-flight bytes).",

            "- Little's Law: L = lambda * W (Average items = arrival rate * average wait time).",
          ],
        },
      ],
    },
  ]

  console.log("📄 Generating authentic academic PDF files for StudyStack...")

  for (const s of samples) {
    const filename = await createPDF(
      s.title,

      s.course,

      s.type,

      s.by,

      s.sections,
    )

    const stats = fs.statSync(path.join(uploadDir, filename))

    const sizeStr = `${(stats.size / 1024).toFixed(1)} KB`

    db.prepare(`
      UPDATE resources 
      SET file_path = ?, file_size = ?
      WHERE id = ?
    `).run(filename, sizeStr, s.id)

    console.log(`✅ Created PDF for "${s.title}" -> ${filename} (${sizeStr})`)
  }

  console.log("🎉 All sample resources now have real PDF files!")
}

generateAllSamplePDFs().catch(console.error)
